### PR TITLE
Fix ncks append without data or metadata options

### PR DESCRIPTION
**Pull request by lizaclark**
This PR addresses Issue #22 by allowing `ncks` to use `-H`, `-m` and `-M` as options with `-A` to append without data, without metadata, and without global/group metadata, respectively, when NCO version >= 4.3.7.

### CODE REVIEW

**Comment by jhamman** [comment]
@lizaclark - can you sort out the merge conflict? Other than that, this looks great.

**Comment by lizaclark** [comment]
@jhamman : I'm not sure which version of code to keep in 
https://github.com/nco/pynco/blob/master/nco/nco.py#L151-L160 or the code in https://github.com/nco/pynco/pull/23/files#diff-0d4fc5047b5b6f70c632a85bfa2728dcR153. This wasn't something I changed, and I'm not sure which is newer.

**Comment by jhamman** [comment]
Hmmm, good question.  I think we should let @hmb1 provide some input on that.

**Comment by jhamman** [comment]
@lizaclark - I think we can close this because @hmb1 pulled in your changes in #24. Let me know if I've missed something.

**Pull request closed without merging**
