### PR TITLE
Now able to provide temporary files when no output files are specified

### LINKED ISSUE #37: Error calling NCO command with tempfile helper
I am attempting to use the Python NCO bindings for calling an NCO command using the [tempfile helper feature](https://pynco.readthedocs.io/en/latest/#tempfile-helpers). For example:

```
nco = Nco()
temp_netcdf_file = nco.ncpdq(input=arguments.netcdf_precip,
                             options=["-a \"-lat,lon,time\""])
```
My expectation from the above is that I will receive a string value with the name of the temporary NetCDF file created as a result of the NCO command. (Or maybe it will be a file object? The return type for this usage is unclear from the documentation.)

When I run the above I get an error:

```nco.nco.NCOException: (returncode:1) b''```

When I step through the `nco.py` code I see the command appears to be properly parsed:  

`cmd: <class 'list'>: ['/home/james/miniconda3/envs/climate/bin/ncpdq', '-a', '"-lat,lon,time"']`

However, when the command is called (line 263) it gets unexpected return values, resulting in the above-mentioned exception.

I can run the command in a terminal on Linux (Ubuntu 18.04) without issue, although in that case I am specifying an output file.

I have seen [similar behavior](https://stackoverflow.com/questions/48627509/pynco-error-when-issuing-ncks-command-unexpected-bytes-object-instead-of-strin) the previous time I attempted to use this package, perhaps these two issues are related?

Thanks in advance for any help with this.

### PR DESCRIPTION
**Pull request by monocongo**
Some updates to resolve #37, still some clean up left to do to sort out leftover code that is in place (I think) to handle temporary files (I left it alone, not certain yet of its purpose and/or if working in any way, but it doesn't appear to be). Some tests are commented out since functionality has been reduced, e.g. we're no longer able to pass brackets in input file and have the shell expand these since we've eliminated shell=True (a security vulnerability mentioned in #33) -- not sure if this is a deal breaker, if so then it may not be too tricky to accommodate.

All tests pass now (several were broken) and the code is working well when used in a [script](https://github.com/monocongo/climate_indices/blob/master/scripts/process_grid_ufunc.py#L864) where I use a temporary file with `ncpdq`.

### CODE REVIEW

**Comment by monocongo** [comment]
I have updated with a new option `use_shell` which will allow the user to specify the `shell=True` setting within the underlying `subprocess()` call that's used to launch the NCO command. Hopefully, this is sufficient/reasonable, and a good resolution to #33 as well.

**Comment by monocongo** [comment]
Import issues causing broken Travis builds with 2.7, my apologies I'm not very adept with that and easily get trapped in the weeds...

**Comment by jhamman** [comment]
A questions and comments. 

1. I think I'm okay dropping Python 2 now. Everyone is basically doing that now so I don't see why we should be supporting it anymore.
2. I'm a little worries about the number of changes to attribute names here. I personally appreciate the pep8 cleanup but some of these could break others stuff. Thoughts?
3. Can we just remove `ncdump`? I don't think its useful.

**Comment by monocongo** [comment]
Yes, I thought about the conversion to snake_case on the attribute names in the public function signatures after making the updates. You're right, this will introduce backward compatibility issues, unnecessarily. 

No sense in keeping `ncdump` as far as I can tell, especially since it's not a part of NCO proper.

I will make the proposed changes to the branch, hopefully within the next day or two. Thanks for your help!

**Comment by monocongo** [comment]
The updated code is now ready for another review. BTW it appears to run OK under 2.7.

**Comment by monocongo** [comment]
@jhamman BTW I applied [black](https://black.readthedocs.io/en/stable/index.html) formatting, and now regret it, in that this was a bit heavy-handed and out-of-scope. Let me know if you want me to back that out.

**Comment by hmb1** [comment]
lmods look fine to me !!

**Comment by hmb1** [comment]
Hi There,
I have some SCRIP NetCDF files to process and I am wondering what the standards are with respect to the polar regions and wrapping ( grid cells that span the Greenwich meridian or the Date line)

The SCRIP file I have has some polar cells that are very wide in longitude (>100 degrees) and very narrow in latitude. ( < 0.5 degrees). It also has some cells that cross the Greenwich meridian ( longitude goes from ( 359.7505422628756833 - 0.2494577371223946 ).

I need an unambiguous way to differenciate between these two cell types.
Is this something that you have come across before ?
Are wrapped cells even legal in SCRIP ?
Any help greatly appreciated.
Thanks

...Henry

**Comment by jhamman** [comment]
I think we should also ask @kwilcox to take a look here if he has time. If no other comments pop up, I'll merge on Friday.

**Comment by monocongo** [comment]
And I'm glad, @czender, to finally be able to make a contribution, albeit in a small way, to the NCO project. The software, along with the helpful support on the discussion forums, has been invaluable over the years.

**Comment by kwilcox** [comment]
Thanks for the contrib @monocongo!

I'm in favor of the merge with the assumption the next release will get a major bump (`1.0.0` even?!?!) to signify the default interface has changed. Users could (I do) assume that `shell=True` is the default and that `pynco` will fall back to the non-shell command. I'll have to go through and add in the `shell=True` in a ton of places. I don't think it's worth making `shell=True` the default and adding a deprecation warning that it will move to `shell=False` in the future if we document this change and put it in the release notes.

I don't agree with all of the code formatting changes but would rather have more contributors than get into a never-ending argument over code styling!

**Comment by jhamman** [comment]
@monocongo and @kwilcox -  have we come to a consensus here? I'm happy to make a 1.0 release following the merge here. Thoughts?

**Comment by monocongo** [comment]
Yes, @jhamman, after doing a bit more testing on my side I'm now confident that things are working as expected regarding a returned temporary file if no output file is specified. Everything else seems to be in order.

**Comment by jhamman** [comment]
In it goes. Thanks @monocongo!

**Pull request merged**
